apiVersion: v1
kind: Service
metadata:
  name: service-1
  namespace: bookinfo
  labels:
    app: service-1
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: service-1