apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: service-2
    spec:
      containers:
      - name: service-2
        image: maiawayg/service-2:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"